### PR TITLE
Create bme680.py

### PR DESCRIPTION
**Pull request by cristianku**
additional bme680

### CODE REVIEW

**Comment by IvanGirderboot** [comment]
Is this PR still workable?  I'd like to see the 680 implemented and I'd hate to redo work that's already been done.

**Comment by vitormhenrique** [comment]
> Is this PR still workable? I'd like to see the 680 implemented and I'd hate to redo work that's already been done.

It’s barely few lines of code to add new sensors, and if you see my latest comments i’m re writing the entire plugin on the python3 branch, making any change and PR here really worth merging, testing and releasing....

i’ll add the bme680 on the new version, but no ETA on anything....

**Comment by IvanGirderboot** [comment]
Good to know.  I'm happy to help out on the implemention side; it would be great to expose pressure and IAQ in the GUI for the sensors that support it.

**Comment by vitormhenrique** [comment]
Would you mind fixing the conflicts?
I'm fixing some issues here and would like to get all PR's on master

**Comment by thijstriemstra** [comment]
this can be closed (#441 was merged instead).

**Comment by vitormhenrique** [comment]
Closed as it was included on another merge

**Pull request closed without merging**
